format: yamanifest
version: 1.0
---
work/access-om3-MOM6-CICE6-WW3:
  fullpath: /g/data/vk83/prerelease/apps/spack/1.1/release/linux-x86_64/access3-2026.03.000-pjsvvtsfxubgiekl6gsmhzyjo2obmknr/bin/access-om3-MOM6-CICE6-WW3
  hashes:
    binhash: da53d4e03f7b17729a3f9c1d8e0c3530
    md5: 70c98c79303f525fd9a4451b9ff80981
