format: yamanifest
version: 1.0
---
work/INPUT/IAF.atm_ave.1958.nc:
  fullpath: /g/data/tm70/as2285/making_inputs/om3-scripts/make_iaf/IAF.atm_ave.1958.nc
  hashes:
    binhash: 0036da449a9d602701adb07f1ab2e85e
    md5: 428aaf06daa30f80e4f31b7f41eb6cc0
work/INPUT/IAF.atm_pt.1958.nc:
  fullpath: /g/data/tm70/as2285/making_inputs/om3-scripts/make_iaf/IAF.atm_pt.1958.nc
  hashes:
    binhash: 44f5d3340a6d7d2fc0962b5b25a1b3ab
    md5: f3314a13fe0db2428097a40803e5f10c
work/INPUT/IAF.rof_ave.1958.nc:
  fullpath: /g/data/tm70/as2285/making_inputs/om3-scripts/make_iaf/IAF.rof_ave.1958.nc
  hashes:
    binhash: e8c60f6fe71eeb6b968ec41aecbd96e5
    md5: 729eac0b16e6e89820777e1c8a9a3fd1
work/INPUT/JRA55do-datm-ESMFmesh.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/share/meshes/share/2026.01.21/JRA55do-datm-ESMFmesh.nc
  hashes:
    binhash: c0e9a071f20670930d0e117f13399d78
    md5: 0ecb68f878b91b8adc90838e2c413914
work/INPUT/JRA55do-drof-ESMFmesh.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/share/meshes/share/2026.01.21/JRA55do-drof-ESMFmesh.nc
  hashes:
    binhash: 9f3ee3ce42e776fcbee8026e0c3880f5
    md5: bf62c4e7786ddfbe56d61b3074d5d16d
work/INPUT/access-om2-100km-ESMFmesh.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/share/meshes/global.100km/2024.01.25/access-om2-100km-ESMFmesh.nc
  hashes:
    binhash: 1ef89b82613d3ef0e903df4aeeb395ce
    md5: 44e508ac57b244fc357faf5b12933bed
work/INPUT/access-om2-100km-nomask-ESMFmesh.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/share/meshes/global.100km/2024.01.25/access-om2-100km-nomask-ESMFmesh.nc
  hashes:
    binhash: 38605aedd850ec5c9d208258f2030166
    md5: 9b7120a42b5cb587492e7c31791eb549
work/INPUT/bottom_roughness.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/mom/tidal_external_files/global.100km/2025.09.22/bottom_roughness.nc
  hashes:
    binhash: e28f832d8cf239fb52e8a835047c9529
    md5: 014f9b95036b9e5a54a24e3643de675b
work/INPUT/chl_globcolour_monthly_clim.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/mom/chlorophyll/global.100km/2025.11.25/chl_globcolour_monthly_clim.nc
  hashes:
    binhash: 5e580f19cb229602926802917f24312c
    md5: d18a52a5e8c7e67de67e0924580f6a10
work/INPUT/iced.1900-01-01-10800.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/cice/initial_conditions/global.100km/2023.07.28/iced.1900-01-01-10800.nc
  hashes:
    binhash: 414174d244807698f8c919f763d3d51d
    md5: 87c012d60c58c65bb56caa98779e5e51
work/INPUT/kmt.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/cice/grids/global.100km/2024.05.14/kmt.nc
  hashes:
    binhash: 670a7fb52cdc440673304d9a775b3dac
    md5: 4dae75252ac93467f10ea26e833e13d2
work/INPUT/make_iaf.py:
  fullpath: /g/data/tm70/as2285/making_inputs/om3-scripts/make_iaf/make_iaf.py
  hashes:
    binhash: bfed6b4fb060520e136722b9c19b0276
    md5: c8e5a1c3c03219bcb9e3d7355541e5c9
work/INPUT/ocean_hgrid.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/mom/grids/mosaic/global.100km/2020.05.30/ocean_hgrid.nc
  hashes:
    binhash: 3526d89ffb639455c6a1218f5139d5b2
    md5: 51f58be0f4ea6da2cb438a893f95c689
work/INPUT/ocean_vgrid.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/mom/grids/vertical/share/2025.03.12/ocean_vgrid.nc
  hashes:
    binhash: 9c1f82b7ea91a8647c8857c02676a7a5
    md5: 66f71f2b24bd00b1c220787505e0106e
work/INPUT/salt_sfc_restore.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/mom/surface_salt_restoring/global.100km/2025.10.24/salt_sfc_restore.nc
  hashes:
    binhash: c1a439bdf28b6a801317e59f6c6d0f3f
    md5: aa31093850132ba8601ae94e74d6b848
work/INPUT/tideamp.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/mom/tidal_external_files/global.100km/2025.09.22/tideamp.nc
  hashes:
    binhash: 10931d9f5303f728e1bf796b8736613a
    md5: 9bcd9d203632a58221a53b3f7ca51622
work/INPUT/topog.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/share/grids/global.100km/2020.10.22/topog.nc
  hashes:
    binhash: 101cb5069e11e9f3196a5a6804fa0780
    md5: 4e13d88001b646f3cf4f1c3b8db59f91
work/INPUT/woa23_ts_01_mom.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/mom/initial_conditions/global.100km/2025.10.24/woa23_ts_01_mom.nc
  hashes:
    binhash: 3187b31900308c4738ae4bb9cd9d3e94
    md5: c6e87eaa93953a8fbe7862fe28f8a546
