#!/usr/bin/env python
"""Case-local payu-run entrypoint with ACCESS-OM3 DICE component metadata."""


def patch_dice_component():
    import payu.models.cesm_cmeps as cesm_cmeps

    cesm_cmeps.component_info.setdefault(
        "dice",
        {"config_files": ["dice_in", "dice.streams.xml"]},
    )


patch_dice_component()

from payu.subcommands.run_cmd import runscript

runscript()
